Iiscrum 1560
digiapulssi/zabbix-monitoring-scripts pull request #64
Opened 2021-03-22 08:17 UTC by ansalapo

The rotated logfile is located by the inode of the file. But the inode is unique only per filesystem. When search from entire disk, there may be multiple results with same inode number. Therefore current implementation assumes that rotated logfile is in the same folder as active logfile.

2021-03-22 08:45 UTC, kompa3 requested changes
Good!

2021-03-22 08:45 UTC, kompa3 commented on etc/zabbix/scripts/rsync_logs.sh
> +
set -e

2021-03-22 08:45 UTC, kompa3 commented on etc/zabbix/scripts/rsync_logs.sh
> +  rsync -za --append -e "ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null" $OLDLOGFILEPATH rsync@$DESTINATIONSERVER:$DESTINATIONPATH
Please add quotes around $OLDLOGFILEPATH so that it will work also if the path contains spaces

2021-03-22 08:45 UTC, kompa3 commented on etc/zabbix/scripts/rsync_logs.sh
> +  OLDLOGFILEPATH=$(find "$OLDLOGFILEPATH" -inum "$INODE")
Please handle the case if you cannot find a rotated file with the old inode

2021-03-22 08:45 UTC, kompa3 commented on etc/zabbix/scripts/rsync_logs.sh
> +  cat > $RSYNCVARS << EOL
Even though $RSYNCVARS should normally not contain spaces, please still add quotes around it so that it won't break if it some day will contain spaces

2021-03-22 08:45 UTC, kompa3 commented on etc/zabbix/scripts/rsync_logs.sh
> +SOURCEFILE=$1
Please add quotes around $1 so that the script will not break if it contains spaces

2021-03-22 08:45 UTC, kompa3 commented on etc/zabbix/scripts/rsync_logs.sh
> +    rsync -za --append -e "ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null" $SOURCEFILE rsync@$DESTINATIONSERVER:$DESTINATIONPATH
Please add quotes around $SOURCEFILE as well

2021-03-24 05:44 UTC, ansalapo commented on etc/zabbix/scripts/rsync_logs.sh
> +
Done

2021-03-24 05:44 UTC, ansalapo commented on etc/zabbix/scripts/rsync_logs.sh
> +  rsync -za --append -e "ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null" $OLDLOGFILEPATH rsync@$DESTINATIONSERVER:$DESTINATIONPATH
Done

2021-03-24 05:44 UTC, ansalapo commented on etc/zabbix/scripts/rsync_logs.sh
> +  OLDLOGFILEPATH=$(find "$OLDLOGFILEPATH" -inum "$INODE")
`if [ ! -z "$OLDLOGFILEPATH" ]; then`

2021-03-24 05:44 UTC, ansalapo commented on etc/zabbix/scripts/rsync_logs.sh
> +  cat > $RSYNCVARS << EOL
Done

2021-03-24 05:44 UTC, ansalapo commented on etc/zabbix/scripts/rsync_logs.sh
> +SOURCEFILE=$1
Done

2021-03-24 05:45 UTC, ansalapo commented on etc/zabbix/scripts/rsync_logs.sh
> +    rsync -za --append -e "ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null" $SOURCEFILE rsync@$DESTINATIONSERVER:$DESTINATIONPATH
Done

2021-03-24 06:28 UTC, kompa3 approved these changes

2021-03-24 07:09 UTC, merged